### ISSUE TITLE
legacy directory is missing when build the wheel

### ISSUE THREAD

**Issue by carlosal1015** [maroba/findiff#88]
**Describe the bug**

When I install the module `findiff` with pip, the directory legacy exists because is there in [findiff-0.11.1-py3-none-any.whl](https://files.pythonhosted.org/packages/a9/d8/5a382a92cc618ad5c7e89e089f4aebb29af6870dcccdf12581ae6fd47ac5/findiff-0.11.1-py3-none-any.whl).
But, if follow [PEP 517](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)) then the legacy directory is missing.

**To Reproduce**

```
docker run -it --rm archlinux:base-devel
pacman -Syu
pacman -S git
git clone https://github.com/maroba/findiff.git
cd findiff
git checkout tags/0.11.1
pacman -S python-build python-setuptools python-wheel
python -m build --wheel --skip-dependency-check --no-isolation
pacman -S unzip
cd dist
ls
unzip *.whl

python -m venv .venv
source .venv/bin/activate
pip install findiff
cd .venv/lib/python3.12/site-packages/findiff
ls
ls legacy
```

```console
$ python
Python 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import findiff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/findiff/__init__.py", line 26, in <module>
    from .compatible import Coef, Coefficient, FinDiff, Id
  File "/usr/lib/python3.12/site-packages/findiff/compatible.py", line 4, in <module>
    from findiff.legacy.operators import _FinDiff
ModuleNotFoundError: No module named 'findiff.legacy'
>>> 
```

**Expected behavior**

legacy directory inside the wheel.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version N/A

[![asciicast](https://asciinema.org/a/694537.svg)](https://asciinema.org/a/694537)

**Comment by maroba** [comment]
Thanks for reporting! I fixed the pyproject.toml and submitted version 0.11.2 to PyPi. It should work now. Can you check, please? Thanks!

**Comment by carlosal1015** [comment]
Thanks for quick fix, is fixed now.
```
==> Making package: python-findiff 0.11.2-1 (Thu 12 Dec 2024 03:29:40 PM -05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib/findiff
copying findiff/__init__.py -> build/lib/findiff
copying findiff/coefs.py -> build/lib/findiff
copying findiff/compatible.py -> build/lib/findiff
copying findiff/grids.py -> build/lib/findiff
copying findiff/operators.py -> build/lib/findiff
copying findiff/pde.py -> build/lib/findiff
copying findiff/stencils.py -> build/lib/findiff
copying findiff/symbolic.py -> build/lib/findiff
copying findiff/utils.py -> build/lib/findiff
copying findiff/vector.py -> build/lib/findiff
creating build/lib/findiff/legacy
copying findiff/legacy/__init__.py -> build/lib/findiff/legacy
copying findiff/legacy/diff.py -> build/lib/findiff/legacy
copying findiff/legacy/operators.py -> build/lib/findiff/legacy
running egg_info
creating findiff.egg-info
writing findiff.egg-info/PKG-INFO
writing dependency_links to findiff.egg-info/dependency_links.txt
writing requirements to findiff.egg-info/requires.txt
writing top-level names to findiff.egg-info/top_level.txt
writing manifest file 'findiff.egg-info/SOURCES.txt'
reading manifest file 'findiff.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'findiff.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/findiff
copying build/lib/findiff/__init__.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/coefs.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/compatible.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/grids.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/operators.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/pde.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/stencils.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/symbolic.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/utils.py -> build/bdist.linux-x86_64/wheel/./findiff
copying build/lib/findiff/vector.py -> build/bdist.linux-x86_64/wheel/./findiff
creating build/bdist.linux-x86_64/wheel/findiff/legacy
copying build/lib/findiff/legacy/__init__.py -> build/bdist.linux-x86_64/wheel/./findiff/legacy
copying build/lib/findiff/legacy/diff.py -> build/bdist.linux-x86_64/wheel/./findiff/legacy
copying build/lib/findiff/legacy/operators.py -> build/bdist.linux-x86_64/wheel/./findiff/legacy
running install_egg_info
Copying findiff.egg-info to build/bdist.linux-x86_64/wheel/./findiff-0.11.2-py3.12.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/findiff-0.11.2.dist-info/WHEEL
creating '/tmp/makepkg/python-findiff/src/findiff-0.11.2/dist/.tmp-6u58g25_/findiff-0.11.2-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'findiff/__init__.py'
adding 'findiff/coefs.py'
adding 'findiff/compatible.py'
adding 'findiff/grids.py'
adding 'findiff/operators.py'
adding 'findiff/pde.py'
adding 'findiff/stencils.py'
adding 'findiff/symbolic.py'
adding 'findiff/utils.py'
adding 'findiff/vector.py'
adding 'findiff/legacy/__init__.py'
adding 'findiff/legacy/diff.py'
adding 'findiff/legacy/operators.py'
adding 'findiff-0.11.2.dist-info/LICENSE'
adding 'findiff-0.11.2.dist-info/METADATA'
adding 'findiff-0.11.2.dist-info/WHEEL'
adding 'findiff-0.11.2.dist-info/top_level.txt'
adding 'findiff-0.11.2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built findiff-0.11.2-py3-none-any.whl
==> Starting check()...
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /tmp/makepkg/python-findiff/src/findiff-0.11.2
configfile: pyproject.toml
plugins: typeguard-4.3.0, jaxtyping-0.2.36, anyio-4.6.2.post1, cov-5.0.0
collected 149 items                                                                                                                                                                        

tests/test_bugs.py ......                                                                                                                                                            [  4%]
tests/test_coefs.py ...............                                                                                                                                                  [ 14%]
tests/test_diff.py .............                                                                                                                                                     [ 22%]
tests/test_findiff.py s...............................s.                                                                                                                             [ 45%]
tests/test_operators.py ...................                                                                                                                                          [ 58%]
tests/test_pde.py .............                                                                                                                                                      [ 67%]
tests/test_pde_old.py ...........s..                                                                                                                                                 [ 76%]
tests/test_scaling.py .....                                                                                                                                                          [ 79%]
tests/test_stencils.py ............                                                                                                                                                  [ 87%]
tests/test_symbolic.py ....                                                                                                                                                          [ 90%]
tests/test_utils.py ....                                                                                                                                                             [ 93%]
tests/test_vector.py ..........                                                                                                                                                      [100%]

============================================================================== 146 passed, 3 skipped in 3.62s ==============================================================================
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "python-findiff"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-findiff 0.11.2-1 (Thu 12 Dec 2024 03:29:51 PM -05)
```

```
$ pacman -Ql python-findiff 
python-findiff /usr/
python-findiff /usr/lib/
python-findiff /usr/lib/python3.12/
python-findiff /usr/lib/python3.12/site-packages/
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/LICENSE
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/METADATA
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/RECORD
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/WHEEL
python-findiff /usr/lib/python3.12/site-packages/findiff-0.11.2.dist-info/top_level.txt
python-findiff /usr/lib/python3.12/site-packages/findiff/
python-findiff /usr/lib/python3.12/site-packages/findiff/__init__.py
python-findiff /usr/lib/python3.12/site-packages/findiff/coefs.py
python-findiff /usr/lib/python3.12/site-packages/findiff/compatible.py
python-findiff /usr/lib/python3.12/site-packages/findiff/grids.py
python-findiff /usr/lib/python3.12/site-packages/findiff/legacy/
python-findiff /usr/lib/python3.12/site-packages/findiff/legacy/__init__.py
python-findiff /usr/lib/python3.12/site-packages/findiff/legacy/diff.py
python-findiff /usr/lib/python3.12/site-packages/findiff/legacy/operators.py
python-findiff /usr/lib/python3.12/site-packages/findiff/operators.py
python-findiff /usr/lib/python3.12/site-packages/findiff/pde.py
python-findiff /usr/lib/python3.12/site-packages/findiff/stencils.py
python-findiff /usr/lib/python3.12/site-packages/findiff/symbolic.py
python-findiff /usr/lib/python3.12/site-packages/findiff/utils.py
python-findiff /usr/lib/python3.12/site-packages/findiff/vector.py
python-findiff /usr/share/
python-findiff /usr/share/licenses/
python-findiff /usr/share/licenses/python-findiff/
python-findiff /usr/share/licenses/python-findiff/LICENSE
```
